services:
  api:
    container_name: ppt-api-v2
    build:
      context: ./PersonalPortfolioTrackerAPI/PersonalPortfolioTracker
    ports:
      - "5034:5034"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://+:5034"
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      ConnectionStrings__DefaultConnection: ${DB_CONNECTION}
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - ./PersonalPortfolioTrackerAPI/PersonalPortfolioTracker/Storage:/app/Storage
  frontend:
    container_name: ppt-fe-v2
    build:
      context: ./PersonalPortfolioTrackerFE
      dockerfile: Dockerfile
    ports:
      - "5176:80"
    environment:
      TZ: Asia/Ho_Chi_Minh
    depends_on:
      - api