// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalPortfolioTracker.Data;

#nullable disable

namespace PersonalPortfolioTracker.Migrations
{
    [DbContext(typeof(PortfolioTrackerContext))]
    [Migration("20260703152216_InitialAzureDb")]
    partial class InitialAzureDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonalPortfolioTracker.Data.Entities.AccountSnapshots", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AccountID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Cycle")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalBalance")
                        .HasColumnType("decimal(28, 8)");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "AccountId", "Cycle" }, "IX_AccountSnapshots_Account_Cycle")
                        .HasFilter("([IsDeleted]=(0))");

                    b.ToTable("AccountSnapshots");
                });

            modelBuilder.Entity("PersonalPortfolioTracker.Data.Entities.Accounts", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("BrokerAccountNo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(28, 8)");

                    b.Property<decimal>("InvestedBalance")
                        .HasColumnType("decimal(28, 8)");

                    b.Property<Guid>("InvestorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("InvestorID");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("TotalBalance")
                        .HasColumnType("decimal(28, 8)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "InvestorId", "Name" }, "IX_Accounts")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("PersonalPortfolioTracker.Data.Entities.AuditLogs", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EntityID");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("InvestorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("InvestorID");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("ID");

                    b.HasIndex("InvestorId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("PersonalPortfolioTracker.Data.Entities.Holdings", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AccountID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<decimal>("InvestmentCost")
                        .HasColumnType("decimal(28, 8)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(28, 8)");

                    b.Property<decimal?>("TargetBuy")
                        .HasColumnType("decimal(28, 8)");

                    b.Property<decimal?>("TargetSell")
                        .HasColumnType("decimal(28, 8)");

                    b.Property<Guid>("TickerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TickerID");

                    b.Property<decimal>("TotalInvestmentCost")
                        .HasColumnType("decimal(28, 8)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("ID");

                    b.HasIndex("TickerId");

                    b.HasIndex(new[] { "AccountId", "TickerId" }, "IX_Holdings")
                        .IsUnique();

                    b.ToTable("Holdings");
                });

            modelBuilder.Entity("PersonalPortfolioTracker.Data.Entities.Investors", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HashPassword")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "Email" }, "IX_Investors")
                        .IsUnique();

                    b.ToTable("Investors");
                });

            modelBuilder.Entity("PersonalPortfolioTracker.Data.Entities.TickerTypes", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "Code" }, "IX_TickerTypes")
                        .IsUnique();

                    b.ToTable("TickerTypes");
                });

            modelBuilder.Entity("PersonalPortfolioTracker.Data.Entities.Tickers", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("MarketPrice")
                        .HasColumnType("decimal(38, 18)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("TickerTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TickerTypeID");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("ID");

                    b.HasIndex("ID", "TickerTypeId")
                        .HasDatabaseName("IX_Tickers_Summary_Optimized")
                        .HasFilter("([IsDeleted]=(0))");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ID", "TickerTypeId"), new[] { "MarketPrice", "Symbol" });

                    b.HasIndex(new[] { "Symbol" }, "IX_Tickers")
                        .IsUnique();

                    b.HasIndex(new[] { "TickerTypeId", "Symbol" }, "IX_Tickers_Type")
                        .HasFilter("([ISDELETED]=(0))");

                    b.ToTable("Tickers");
                });

            modelBuilder.Entity("PersonalPortfolioTracker.Data.Entities.Transactions", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AccountID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<decimal?>("Fee")
                        .HasColumnType("decimal(28, 8)");

                    b.Property<decimal?>("FeeRate")
                        .HasColumnType("decimal(12, 6)");

                    b.Property<decimal?>("GrossAmount")
                        .HasColumnType("decimal(28, 8)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("NetAmount")
                        .HasColumnType("decimal(28, 8)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("PIT")
                        .HasColumnType("decimal(28, 8)")
                        .HasColumnName("PIT");

                    b.Property<decimal?>("PITRate")
                        .HasColumnType("decimal(12, 6)")
                        .HasColumnName("PITRate");

                    b.Property<decimal?>("PreInvestmentCost")
                        .HasColumnType("decimal(28, 8)");

                    b.Property<decimal?>("PreQuantity")
                        .HasColumnType("decimal(28, 8)");

                    b.Property<decimal?>("PreTotalInvestmentCost")
                        .HasColumnType("decimal(28, 8)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(28, 8)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(28, 8)");

                    b.Property<decimal?>("RealizedPnL")
                        .HasColumnType("decimal(28, 8)");

                    b.Property<decimal?>("RealizedPnLRate")
                        .HasColumnType("decimal(12, 6)")
                        .HasColumnName("RealizedPnLRate");

                    b.Property<Guid>("TickerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TickerID");

                    b.Property<DateOnly>("TradeDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(CONVERT([date],sysdatetime()))");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ID");

                    b.HasIndex("TickerId");

                    b.HasIndex(new[] { "AccountId", "TradeDate", "CreatedAt", "TransactionType", "TickerId" }, "IX_Transactions_Filter")
                        .HasFilter("([IsDeleted]=(0))");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("PersonalPortfolioTracker.Data.Entities.AccountSnapshots", b =>
                {
                    b.HasOne("PersonalPortfolioTracker.Data.Entities.Accounts", "Account")
                        .WithMany("AccountSnapshots")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK_AccountSnapshots_Accounts");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("PersonalPortfolioTracker.Data.Entities.Accounts", b =>
                {
                    b.HasOne("PersonalPortfolioTracker.Data.Entities.Investors", "Investor")
                        .WithMany("Accounts")
                        .HasForeignKey("InvestorId")
                        .IsRequired()
                        .HasConstraintName("FK_Accounts_Investors");

                    b.Navigation("Investor");
                });

            modelBuilder.Entity("PersonalPortfolioTracker.Data.Entities.AuditLogs", b =>
                {
                    b.HasOne("PersonalPortfolioTracker.Data.Entities.Investors", "Investor")
                        .WithMany("AuditLogs")
                        .HasForeignKey("InvestorId")
                        .IsRequired()
                        .HasConstraintName("FK_AuditLogs_Investors");

                    b.Navigation("Investor");
                });

            modelBuilder.Entity("PersonalPortfolioTracker.Data.Entities.Holdings", b =>
                {
                    b.HasOne("PersonalPortfolioTracker.Data.Entities.Accounts", "Account")
                        .WithMany("Holdings")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK_Holdings_Accounts");

                    b.HasOne("PersonalPortfolioTracker.Data.Entities.Tickers", "Ticker")
                        .WithMany("Holdings")
                        .HasForeignKey("TickerId")
                        .IsRequired()
                        .HasConstraintName("FK_Holdings_Tickers");

                    b.Navigation("Account");

                    b.Navigation("Ticker");
                });

            modelBuilder.Entity("PersonalPortfolioTracker.Data.Entities.Tickers", b =>
                {
                    b.HasOne("PersonalPortfolioTracker.Data.Entities.TickerTypes", "TickerType")
                        .WithMany("Tickers")
                        .HasForeignKey("TickerTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Tickers_TickerTypes");

                    b.Navigation("TickerType");
                });

            modelBuilder.Entity("PersonalPortfolioTracker.Data.Entities.Transactions", b =>
                {
                    b.HasOne("PersonalPortfolioTracker.Data.Entities.Accounts", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK_Transactions_Accounts");

                    b.HasOne("PersonalPortfolioTracker.Data.Entities.Tickers", "Ticker")
                        .WithMany("Transactions")
                        .HasForeignKey("TickerId")
                        .IsRequired()
                        .HasConstraintName("FK_Transactions_Tickers");

                    b.Navigation("Account");

                    b.Navigation("Ticker");
                });

            modelBuilder.Entity("PersonalPortfolioTracker.Data.Entities.Accounts", b =>
                {
                    b.Navigation("AccountSnapshots");

                    b.Navigation("Holdings");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PersonalPortfolioTracker.Data.Entities.Investors", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("AuditLogs");
                });

            modelBuilder.Entity("PersonalPortfolioTracker.Data.Entities.TickerTypes", b =>
                {
                    b.Navigation("Tickers");
                });

            modelBuilder.Entity("PersonalPortfolioTracker.Data.Entities.Tickers", b =>
                {
                    b.Navigation("Holdings");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
